version: "3"

services:
  proxy:
    container_name: pr-proxy
    restart: always
    build: ./proxy
    ports:
      - "80:80"
    extra_hosts:
      - host.docker.internal:host-gateway

  frontend:
    container_name: pr-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"

  backend:
    container_name: pr-backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    extra_hosts:
      - host.docker.internal:host-gateway