spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/personalrecord
        username: pr_sys
        password: 12345
    data:
        redis:
            host: localhost
            port: 6379