spring:
    profiles:
        active: dev
        # active: prod

server:
    port: 8081

cors:
    allowed:
        origins: http://localhost:3000

# mybatis
mybatis:
    mapper-locations: classpath:mybatis/mapper/**/**.xml
