spring:
    profiles:
        active: 
            # - dev
            - jwt
            - prod

server:
    port: 8081

cors:
    allowed:
        origins: http://3.39.239.240

# mybatis
mybatis:
    mapper-locations: classpath:mybatis/mapper/**/**.xml
